return {
	cmd = { "harper-ls", "--stdio" },
	filetypes = {
		"markdown",
		"text",
		"gitcommit",
		"html",
		"css",
		"javascript",
		"typescript",
		"lua",
		"python",
		"rust",
		"go",
		"java",
		"c",
		"cpp",
		"yaml",
		"json",
		"toml",
		"vim",
		"sh",
		"bash",
	},
	root_markers = {
		".harper.toml",
		".harper.json",
		"harper.toml",
		"harper.json",
		".git",
		"package.json",
		"Cargo.toml",
		"pyproject.toml",
	},
	single_file_support = true,
	settings = {
		["harper-ls"] = {
			userDictPath = vim.fn.stdpath("config") .. "/spell/en.utf-8.add",
			linters = {
				SentenceCapitalization = false,
			},
			codeActions = {
				ForceStable = true,
			},
		},
	},
}
